### ISSUE TITLE
what's it looks like?

### ISSUE THREAD

**Issue by majorye** [wanxianjia/PSD2HTML#10]
大家说说你们心目中的这个项目，最终是一个什么样的产品，
你是导演，你说了算，哈哈。

**Comment by zeroven** [comment]
1、视觉设计师按照约定规范设计完成PSD；
2、配置原文件信息、模板、组件等参数，运行我们的工具脚本
3、生成HTML页面

**Comment by ghost** [comment]
用户用了叫好的产品，就是好产品。
我觉得，上传一张PSD，就生成一张网页。这中体验好。
至于其他什么组件并不是每个PSD都必须的。配置太多，就容易让人抵触。

--我能修改肖总的comment? 这是什么逻辑～

**Comment by majorye** [comment]
是的，对于我们dev来说， 我们的通病就是， 最求完美， 其实这是错的，我认为， 只要我们解决了一些问题，那我们就进步了， 什么都能解决那是最好，但基本不可能，所以我们要定义我们产品的边界。

**Comment by tengfeiyang** [comment]
想知道PS里的命名要细节到什么程度，适合哪些类型的页面。可以先从运营的页面搞个效果看看
