### ISSUE TITLE
图层命名规则、规划

### ISSUE THREAD

**Issue by wanxianjia** [wanxianjia/PSD2HTML#12]
统一规范

**Comment by ghost** [comment]
组件建议在图层命名前加上"lib_"

**Comment by majorye** [comment]
ok~

**Comment by majorye** [comment]
@xiaowuming  我打算加comp  ,就是component的前缀

**Comment by ghost** [comment]
可以后续讨论，我先用lib_测试

**Comment by majorye** [comment]
please see : https://github.com/wanxianjia/PSD2HTML/issues/13
