### ISSUE TITLE
PSD图层命名规范v0.1

### ISSUE THREAD

**Issue by majorye** [wanxianjia/PSD2HTML#13]
经过了激烈的思想斗争之后，PSD图层命名规范v0.1   终于出炉。

适应场景：

1: PSD的设计规则遵循了FD的栅格设计理论
2: 每个组件可以独立运行，没有任何的依赖关系，如果是盒子的cell，需遵守盒子的规则
3: 所有的交互，都是在组件里面完成，如果有组件间的交互，通过消息通知机制即可，目前暂不考虑
4: PSD的层级关系鲜明，而且层级的顺序和页面的顺序基本一致
5: 已经有了一定的组件库基础

具体规则：

0：所有的命名在是在图层的组上命名，不会对图层有任何的侵入
1： comp{组件名_n}
 --comp：组件(component) 的缩写，目前作为组件的代名词，所有组件层都以其开头
 --组件名：作为和组件的html片段的一种映射关系，须唯一，盒子的组件名就以盒子的cell名命名
 --n：代表有几个该组件，默认为1，即不用_1 
2： layout
     表示需使用栅格的layout，需要几个column， 就使用几个图层组，组名为该column的的css style, 如: grid8 grid-fixed
3：grid16等栅格理论css, 这些都是layout组的节点，而且也必须是layout组的节点
4： 组件里面可以嵌套组件

具体，请参考： https://github.com/wanxianjia/PSD2HTML/blob/master/test/psd/isvhome_Demo.psd

**Comment by wanxianjia** [comment]
运营需求会对图层有侵入：
1、图层名用a- 开头表示链接
2、cssimg-表示需要合并至背景图片

以上为建议，周全，肖总决定。

**Comment by majorye** [comment]
恩，目前的，肖总，可以进展盒子相关的demo工作，接下来，我会考虑组件和一般元素的混合体情况～
