### ISSUE TITLE
psd2html, 与盒子相比，优势在哪？ 劣势在哪？定位在哪？

### ISSUE THREAD

**Issue by majorye** [wanxianjia/PSD2HTML#17]
psd2html, 与盒子相比，优势在哪？ 劣势在哪？

**Comment by starsun** [comment]
我的感嚼是可以结合在一起，形成一个闭环。psd2html可以输出cell、model、layout给盒子，也可以利用盒子的cell、model、layout来生成页面。这么看，我们只是暂时需要借助盒子的cell吗？

**Comment by dian533** [comment]
我觉得这个问题还要从psd2html能实现到何种程度说起，假如pad2html能够做到完全脱离盒子生成比较符合规范的（或者说理想的html代码）那么就能为盒子提供模版或者页面。盒子从此就不再负责页面的生成（或者是只负责由运营自己拼装的页面），专注于可视化编辑和微调，对已有页面的修改、绑定数据源等等。
但在与psd2html项目的各位同学交流过程中，我所得到的信息是目前为止pad2html很难从技术上实现上面理想的功能。对于相对比较规范的页面需要借助盒子提供cell/module/layout层的代码，才能实现。如此我便有些疑问，如此设计师在psd中对cell/module/layout层做的样式上的修改是否能正确的体现在页面上？
另外，我觉得在前期，psd2html对营销页面的作用会比较大，这类页面的特性是周期短对代码质量要求较低，哪怕都用绝对定位来做也无妨，只要在一定程度上满足盒子的规范，同样可以实现可视化编辑。

**Comment by majorye** [comment]
非常细致，谢谢@dian533
其实我也一直在思考它的定位，如果它能在没有任何规则的情况下，生成比较规范的代码，这是大家想要的。 但从目前Adobe开发的API而言，是不可能实现的。

一次性的运营页面，确实可以用它来解决。

那完全符合组件化的页面，也可以用它来解决吗？

对于PD， 只要足够熟悉这些组件，写出一个简单的JSON chuan, 使用它，就可以得到一个页面，就可以review. 就可以给客户看
对于Dev,   只要足够熟悉这些组件，写出一个简单的JSON chuan,
使用它，就可以得到一个页面，省去了他们copy的时间，接下来就是写组件间的信息沟通问题。
...

在 2012年5月16日 下午1:24，dian533 <
reply@reply.github.com

> 写道：
> 
> 我觉得这个问题还要从psd2html能实现到何种程度说起，假如pad2html能够做到完全脱离盒子生成比较符合规范的（或者说理想的html代码）那么就能为盒子提供模版或者页面。盒子从此就不再负责页面的生成（或者是只负责由运营自己拼装的页面），专注于可视化编辑和微调，对已有页面的修改、绑定数据源等等。
> 
> 但在与psd2html项目的各位同学交流过程中，我所得到的信息是目前为止pad2html很难从技术上实现上面理想的功能。对于相对比较规范的页面需要借助盒子提供cell/module/layout层的代码，才能实现。如此我便有些疑问，如此设计师在psd中对cell/module/layout层做的样式上的修改是否能正确的体现在页面上？
> 
> 另外，我觉得在前期，psd2html对营销页面的作用会比较大，这类页面的特性是周期短对代码质量要求较低，哪怕都用绝对定位来做也无法，只要在一定程度上满足盒子的规范，同样可以实现可视化编辑。
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/wanxianjia/PSD2HTML/issues/17#issuecomment-5733775

## 

谢谢,

叶周全

**Comment by dian533** [comment]
@majorye 很不错的想法

根据盒子的经验，我建议项目组可以先重点针对一次性的运营页面，这样可以先让用户用起来，先感受到此工具的好处。那以后拓展功能的时候再推给用户会更方便些。
