### ISSUE TITLE
Problem with language

### ISSUE THREAD

**Issue by ghost** [wanxianjia/PSD2HTML#39]
Hello guys!

I really like the idea of your project and would like to contribute, but that's impossible since I cant understand chinese :(
Can you guide me throught or use english?

thx ^^

ow btw.. is there a similar project to this one on github?

**Comment by majorye** [comment]
Hi  Piotr

thanks for your contribute, very appreciate it.  and also I want to say:
good catch , Priotr. lots of guys in our team
use the native Chinese to submit the code. yes, I agree with u, we should
add some document in English, so you guys
could quick know what the project it is, how it works, what the next
schedule, and also you guys could contribute it easier.

Welcome, Priotr. you are the hero.

Thx

--Major

2012/5/31 Piotr Yordanov <
reply@reply.github.com

> Hello guys!
> 
> I really like the idea of your project and would like to contribute, but
> that's impossible since I cant understand chinese :(
> Can you guide me throught or use english?
> 
> thx ^^
> 
> ow btw.. is there a similar project to this one on github?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/wanxianjia/PSD2HTML/issues/39

## 

谢谢,

叶周全

**Comment by hustcer** [comment]
Thanks for your attention, we will add the English doc this week ~

**Comment by ghost** [comment]
sure :)
I actually noticed the project and realized it was very active, that got my attention :)
btw, are you doing this for research purposes or for some professional work?

Cheers :)

**Comment by hustcer** [comment]
English Docs Added.

**Comment by ghost** [comment]
ah thank you :)
So now another question: can this run without using PS? (Cuz i dont have PS :P )
