### ISSUE TITLE
parseEngine.js  or buildEngine.js ?

### ISSUE THREAD

**Issue by majorye** [wanxianjia/PSD2HTML#8]
目前的psd.js ，里面除了提供PSD 基本的功能外，还提供了一些解析图层的功能，
对于这种解析功能，我们是需要一个解析引擎来处理，所以需要把相关的解析功能，
转移到parseEngine.js  里面去。

**Comment by wanxianjia** [comment]
psd.js为解析psd核心库，不应该掺杂html、css生成的东西。
